name: crate-deployment

on:
  push:
    branches:
      - main

jobs:
  create_deployment:
    name: create_deployment
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: text/json; charset=utf-8" \
            -H "Accept: application/vnd.github.flash-preview+json" \
            https://api.github.com/repos/{$GITHUB_REPOSITORY}/deployments \
            -d '{"ref":"main","description":"deployment created", "required_contexts": []}'